### ISSUE TITLE
Launch Args relates to `Quick Play` always added when launching

### ISSUE THREAD

**Issue by Wst-04d12** [MrShieh-X/console-minecraft-launcher#29] opened 2023-06-10 09:30 UTC
Since Minecraft Snapshot 23w14a, there's a new feature called the `Quick Play Mode`, it simply allow the game to join a specific server/local world/realms instantly after the game has finished its launching and initialization progress, and this such feature is implemented by adding launching arguments, check [this](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w14a#:~:text=function%20to%20call-,QUICK%20PLAY,-Added%20support%20for) by Mojang for details.

But while using CMCL to launch a newer version of Minecraft, say 1.20, these arguments that relate to the Quick Launch was always added.

`--quickPlayPath ${quickPlayPath} --quickPlaySingleplayer ${quickPlaySingleplayer} --quickPlayMultiplayer ${quickPlayMultiplayer} --quickPlayRealms ${quickPlayRealms}` 

Which causing the game to run into the Quick Launch mode with no target level given and showing up like this.

![image](https://github.com/MrShieh-X/console-minecraft-launcher/assets/89057904/0d84c517-05c3-4f9b-a5f5-a3c3800a8ba6)

To solve this, just not adding these arguments as always, but additionally. Maybe even add related settings to the config file?

##update##

Located problem in `src\main\java\com\mrshiehx\cmcl\modules\MinecraftLauncher.java`,  cauze you've done this `minecraftArguments.addAll(argus);` at ln278, the arguments relate to the quick play will just added into the `minecraftArguments` from the `minecraftVersionJsonFile` of the newer versions of the Minecraft. To fix, you can add a filter while reassembling the launch arguments at ln311, within the for iterator.

I mean, add a settings into the config(cmcl.json), and if the user actually set the quickplay to true and provided the target world/server for the quick play in the config file, then assemble all the arguments like the current code from ln311 ~ ln316, and then complete them using the code pattern like the current one for enabling the quick play, elseif the user provided the incomplete information for the quick play, or just set it to false, then just cut off those arguments  in the for iterator at ln311 ~ ln316 by filtering out those `argument.key` by the keyword `quickPlay`, if found, abandon those keys and their value.

Here is the code simply modified by my self, it removes any arguments relate to quick play therefore fixed the issue in a hard-coded way.

(line 310 in src\main\java\com\mrshiehx\cmcl\modules\MinecraftLauncher.java)
>        for (Argument argument : arguments1) {
>            if(!((String)argument.key).contains("quickPlay")){
>                minecraftArguments.add("--" + argument.key);
>                if (argument instanceof ValueArgument) {
>                    minecraftArguments.add(((ValueArgument) argument).value);
>                }
>            }
>        }

One step forward, we can add a variable to represent whether or not enabling the quick play, so we can change the behavior of the code, like this

>        boolean enableQuickPlay = false;
>
>        for (Argument argument : arguments1) {
>            if(!((String)argument.key).contains("quickPlay") || enableQuickPlay){
>                minecraftArguments.add("--" + argument.key);
>                if (argument instanceof ValueArgument) {
>                    minecraftArguments.add(((ValueArgument) argument).value);
>                }
>            }
>        }

and then if it got enabled, fill up those values (don't forget to dock these values to the config and read them from it)

>            ...
>            if (s.contains(source = "${quickPlayPath}")) {
>               minecraftArguments.set(i, s = s.replace(source, String.valueOf(quickPlayPath)));
>            }
>            ...

and that's it.

**Comment by MrShieh-X** [comment] 2023-06-10 14:49
Oh, it's definitely an issue that needs to be fixed, but I've been a little busy lately so it might take a while to get it fixed. I can't believe that someone can give me development suggestions based on understanding the code of this launcher, you must be a big fan of this great launcher :-)

**Comment by MrShieh-X** [comment] 2023-07-13 06:07
This issue is fixed in v2.2, and Quick Play mode can also be used by setting the following configuration.

| Configuration Name | Type | Meaning                                                                                                                                                                                                                                                           |
|--------------------|------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| qpLogFile          | Text | [**Game related**] The log file path (relative to the game directory) of Quick Play (a new feature of Minecraft 1.20, set the following three configurations to start the game and directly enter the save, server or realms, only one item can be set), optional |
| qpSaveName         | Text | [**Game related**] The name of the save that the quick play will join directly                                                                                                                                                                                    |
| qpServerAddress    | Text | [**Game related**] The address (including port) of the server that the quick play will join directly, this configuration also applies to versions prior to 1.20                                                                                                   |
| qpRealmsID         | Text | [**Game related**] The ID of the realms that the quick play will join directly                                                                                                                                                                                    |

The occurrence of this problem is caused by the improper handling of the rules in the arguments in the version json by the launcher.
The `isMeetConditions` method in `com.mrshiehx.cmcl.modules.MinecraftLauncher` has currently been overridden.

**Closed by MrShieh-X** 2023-07-13 06:07 UTC
